dependencies:
    kazoo:
        class: kazoo.client:KazooClient
        hosts: zk


container:
    registry:
        class: lymph.discovery.zookeeper:ZookeeperServiceRegistry
        zkclient: dep:kazoo


event_system:
    class: lymph.events.kombu:KombuEventSystem
    transport: amqp
    hostname: rabbitmq


instances:
    web:
        command: lymph instance --config=conf/web.yml
        port: 4080

    echo:
        command: lymph instance --config=conf/echo.yml
        numprocesses: 3

    ear:
        command: lymph instance --config=conf/ear.yml
        numprocesses: 2
