dependencies:
    kazoo:
        class: kazoo.client:KazooClient
        hosts: zk


container:
    registry:
        class: lymph.discovery.zookeeper:ZookeeperServiceRegistry
        zkclient: dep:kazoo

    events:
        class: lymph.events.kombu:KombuEventSystem
        transport: amqp
        hostname: rabbitmq


instances:
    Web:
        command: lymph instance --config=conf/web.yml
        numprocesses: 2

    Greeting:
        command: lymph instance --config=conf/greeting.yml
        numprocesses: 3

    Listen:
        command: lymph instance --config=conf/listen.yml
        numprocesses: 4


sockets:
    Web:
        port: 4080
