language: python
python:
  - "2.7"
install: "pip install -r requirements.txt"
script:
  - PYTHONPATH=services nosetests --with-lymph
  - python scripts/highlight.py
after_success:
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then export DEPLOY_PAGES=true; fi
  - if [ "$DEPLOY_PAGES" ]; then gem install jekyll && bash scripts/deploy_pages.sh; else echo "not deploying pages"; fi
