language: python
python:
  - "2.7"
install: "pip install -r requirements.txt"
script:
  - PYTHONPATH=services nosetests --with-lymph
  - python scripts/highlight.py
after_success:
  - gem install jekyll
  - bash scripts/deploy_pages.sh
